services:
  frontend:
    image: katsapp_frontend
    ports:
      - "3000:3000"

    env_file: ./frontend/.env
    build: ./frontend
    networks:
      - front-tier

  backend:
    image: katsapp_backend
    networks:
      - back-tier
      - front-tier
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file: ./backend/.env
    build: ./backend

  database:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data:


networks:
  front-tier:
  back-tier:
