name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-project:
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: deploy site via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          rm: true
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/ubuntu/app"

      - name: start the docker compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/app &&
            docker-compose stop &&
            docker-compose build &&
            docker-compose up -d
